### ISSUE TITLE
[Feature Request] Add HLS / DASH support

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [MerlinVR/USharpVideo#12]
Hi, is it possible tu add support for HLS / DASH Livestreams url / formats (m3u8 / mpd)
That would be Awsome
Thanks

**Comment by MerlinVR** [comment]
https://www.renderheads.com/content/docs/AVProVideo/articles/supportedmedia.html AVPro should support those stream formats. This is something that USharpVideo does not need to have any special handling for, you just need to select the stream player mode. If it does not work in VRC, it's likely that VRC's url resolving is breaking on those URLs which would need a canny for VRChat to fix on their end.

**Comment by TomAvecLeVdsl** [comment]
Hi, thanks for your reply, after extended testing it was because the streaming server soft that i was using was not producing a HLS stream compatible with VRC, i had to use nginx to get one ... but thanks for looking into it :)

**Comment by girguy101** [comment]
wait i'm confused. i cant play m3u8 links on usharpvideo v1.0.1 U# video player. what do
