### ISSUE TITLE
How to adjust starting audio?

### ISSUE THREAD

**Issue by Jbkdude1** [MerlinVR/USharpVideo#13]
I have set up a playlist to auto-play when the world is loaded. However, the audio plays at 25% volume, which is far too low. I have tried adjusting the volume variable in the VideoAudioSource object, but the volume upon loading in to a world is always stuck at 25%. What am I doing wrong?

**Comment by MerlinVR** [comment]
At the moment you'd adjust the volume on the slider UI element for the volume.
