### ISSUE TITLE
What types of livestreams are supported?

### ISSUE THREAD

**Issue by SkeletonTechNL** [MerlinVR/USharpVideo#14]
Hey there,
I've been playing around a bit with USharpVideo, and I was trying to get an RTMP stream to work on it, but it would not load the stream. 
Which types of streams are supported as of now?

**Comment by MerlinVR** [comment]
All VRC stream players use AVPro so you'll want to look at the documentation for AVPro's streaming capabilities https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html
