### ISSUE TITLE
Default state to stream

### ISSUE THREAD

**Issue by sveken** [MerlinVR/USharpVideo#15]
Hello,
Is there a way to set the default to stream so i can feed youtube stream into the starting playlist, 
Currently it just states invalid if i try, i have to load the world, swap it to stream, then i can paste the same URL in and it will work

Thanks

**Comment by KrantuZiru** [comment]
Came here looking for the solution to this same issue

**Comment by ChxGuillaume** [comment]
Looking for the same thing, can't find a solution
