### ISSUE TITLE
Twitch stream no video

### ISSUE THREAD

**Issue by artblaster** [MerlinVR/USharpVideo#16]
There seems to be an issue with only twitch streams on the player, the audio plays but the video gets stuck on the countdown from the start at 1. I tested a youtube stream and it worked fine.

I love the player and hope you still support it! Thanks

**Comment by MerlinVR** [comment]
This is an issue with some part of how VRC uses AVPro internally which triggers the audio bug. I'm guessing some piece of their code for the audio source handling toggles the audio sources at some point which breaks AVPro audio. I will be adding a resync button to work around this issue in 1.0
