### ISSUE TITLE
Syncing with quest

### ISSUE THREAD

**Issue by BassBoostedDuck** [MerlinVR/USharpVideo#17]
found this vie a google search for vrchat quest synced video players , does this video player work for both pc and quest on the sdk3?

**Comment by MerlinVR** [comment]
This works on Quest, but you can only use links that directly link to an mp4 or other compatible video file formats. This means no YouTube links. This is a limitation that all VRC video players share since Quest does not have YouTubeDL which is required to resolve URLs that aren't direct links.
