### ISSUE TITLE
Volume for Quest Users

### ISSUE THREAD

**Issue by succubus-sappho** [MerlinVR/USharpVideo#21]
I use this as a cross-platform video player and it works extremely well; however, the volume difference between PC and Quest is insane (the volume level on Quest is far quieter), is there a way to mitigate or fix this?

For details I use direct .mp4 links from bunny.net CDN

**Comment by succubus-sappho** [comment]
A comment from a quest user was this - the volume slider does not work for them, whether at 0 or 100 the volume is the same

**Comment by MerlinVR** [comment]
Are you sure the volume slider works at all in your map? 0 volume on the slider is muted, so if it's not changing then something went wrong and crashed the script. For a volume difference in general I'd just say let them adjust the volume if it's too low, or upload the Quest version of the map with the default volume set higher. 100% on the volume slider is 100% volume on the audio sources, so it's not going to get higher than that.

**Comment by succubus-sappho** [comment]
I see, yes I can confirm the slider works correctly for PC but not for the questies. I suppose I can try making the default volume 100%. I will test this more and update you to see how it goes. The only thing I can think of at the present moment is that Udon is acting weird when people on Quest try to interact with the scripts.

For instance in my world I have buttons that fill the InputField automatically with a predefined VRCUrl and then sends the command to the video controller script OnURLInput. This also does not work for Quest but does on PC

![Capture](https://user-images.githubusercontent.com/86172318/122658975-7bc7d680-d138-11eb-9032-53e67a7b1318.JPG)

**Comment by MerlinVR** [comment]
Input fields on Quest are weird, I'm not sure if they would cause issues when you're attempting to use them like this. https://vrchat.canny.io/quest-creators/p/864-ui-inputfields-are-not-functional-on-quest Also make sure you don't have any custom scripts that could interfere with the video player.

Use the URLButton example script if you want a clickable video change. https://github.com/MerlinVR/USharpVideo/wiki/examples#url-button

**Comment by succubus-sappho** [comment]
Thank you that's actually really useful, after I change the buttons I'm expecting the world will run more smoothly. I hope that is also the issue with the audio indirectly somehow. If not I'll report back and re-open this thread
