### ISSUE TITLE
3D Audio not working

### ISSUE THREAD

**Issue by hackthedev** [MerlinVR/USharpVideo#23]
I dont know how to let it work with 3D Audio and Audio Range.l Its not working for me what do i have to do?

**Comment by MerlinVR** [comment]
You can drag the curve up for the spatial blend on the VideoAudioSource. You can increase the audio range on the U# video player for the video range. 

![image](https://user-images.githubusercontent.com/36685500/124192340-f9b1a900-da79-11eb-8631-e42b40470c56.png)
![image](https://user-images.githubusercontent.com/36685500/124192446-2796ed80-da7a-11eb-920e-afe84251d1f3.png)

**Comment by hackthedev** [comment]
I did change it recording to what you've said but its not working. its still Global and 2D.
![image](https://user-images.githubusercontent.com/40896559/124258229-73569f00-db2d-11eb-8a8e-bcfc23feed75.png)

**Comment by MerlinVR** [comment]
You did not, the green curve needs to be a line along the top.

**Comment by hackthedev** [comment]
Okay I did that too but still. Its not working its even quieter but still global. Although I'm having problems with your player, i have to admit that i really love it, and I've seen it in other world working correctly
![image](https://user-images.githubusercontent.com/40896559/124259011-540c4180-db2e-11eb-82f3-a2e5cb6fc637.png)

**Comment by MerlinVR** [comment]
The falloff distance is way too high for you to hear the falloff. If you want to hear it you need to make the falloff sphere fall inside the room.

**Comment by MerlinVR** [comment]
Also if you're only testing in editor, you need to move the Main Camera game object around to hear what it sounds like. Audio is not affected by your scene view position.

**Comment by hackthedev** [comment]
Oh okay this osunds interesting im gonna try that

**Comment by hackthedev** [comment]
Okay yeah it was because of the ingame camer while testing in editor. this is amazing. anyway thank you a lot.
