### ISSUE TITLE
Using the new automatic resync options added in latest sdk

### ISSUE THREAD

**Issue by Legoman99573** [MerlinVR/USharpVideo#26]
Knowing this is a warning, but I am not sure if its affected currently or not with the latest update.
![image](https://user-images.githubusercontent.com/7460704/125677119-2c98d65c-5d36-4479-9f03-6a6f5d87a068.png)

**Comment by HugoZink** [comment]
Same here. Do we really want to use this option, or is this only meant for basic video players with little/no scripting behind them?

**Comment by MerlinVR** [comment]
You can use it if you want. It's defaulted off because it can supposedly cause hitching in some cases. It's there to keep the audio and video in sync but I don't know how it works under the hood and haven't tested it much so I can't speak for its effectiveness or stability at the moment.
