### ISSUE TITLE
cant paste urls 

### ISSUE THREAD

**Issue by wpg1993** [MerlinVR/USharpVideo#29]
im having an issue where it wont let me put a url in
the script kept saying it was missing 
i put the playurlbutton one in 
compiled it with udon 
still doesnt work
vrcurlfield doesnt work either 
i really wanna get this working for my world so me and quest friends can watch videos together 
![image](https://user-images.githubusercontent.com/78664594/128491469-99261262-3055-417a-a580-1f188ddb2557.png)

**Comment by MerlinVR** [comment]
You need to follow the migration fix for input fields https://docs.vrchat.com/docs/migrating-from-2018-lts-to-2019-lts#empty-control-panel-or-missing-vrcurlinputfield
