### ISSUE TITLE
In Video Mode, couldn't hear the right channel of Audio

### ISSUE THREAD

**Issue by aonocy** [MerlinVR/USharpVideo#30]
In Video Mode, couldn't hear the right channel of Audio.
The following steps will cause problems.

1. Create a new project in Unity (2019.4.29f1).
2. Import VRChat SDK3 World (2021.08.04.15.07_Public), UdonSharp (v0.20.2), and USharpVideo (v1.0.0).
3. Place Plane, VRC World Prefab, and USharpVideo Prefab in Scene.
4. Run Bulid & Test.

This video is used for confirmation.
https://youtu.be/fIrrHUaXpAE?t=185

**Comment by Raybo3D** [comment]
Did you find a solution? I have the same problem and have no idea how to solve it.

**Comment by MerlinVR** [comment]
uncheck the Enable Spatialization checkbox on the VideoAudioSource's VRC Spatial Audio Source component

**Comment by Raybo3D** [comment]
Yeah that worked. Thank you for the quick answer!
