### ISSUE TITLE
error nameplace isValid does not exist

### ISSUE THREAD

**Issue by ChinoFurro** [MerlinVR/USharpVideo#32]
```
Assets\USharpVideo\Scripts\USharpVideoPlayer.cs(1484,21): error CS0234: The type or namespace name 'IsValid' does not exist in the namespace 'Utilities' (are you missing an assembly reference?)

Assets\USharpVideo\Scripts\USharpVideoPlayer.cs(1505,18): error CS0234: The type or namespace name 'IsValid' does not exist in the namespace 'Utilities' (are you missing an assembly reference?)

Assets\USharpVideo\Scripts\USharpVideoPlayer.cs(1527,18): error CS0234: The type or namespace name 'IsValid' does not exist in the namespace 'Utilities' (are you missing an assembly reference?)

Assets\USharpVideo\Scripts\USharpVideoPlayer.cs(1559,21): error CS0234: The type or namespace name 'IsValid' does not exist in the namespace 'Utilities' (are you missing an assembly reference?)
```

**Comment by MerlinVR** [comment]
This is usually due to Unity corrupting the SDK, try following the steps at https://docs.vrchat.com/docs/migrating-from-2018-lts-to-2019-lts#empty-control-panel-or-missing-vrcurlinputfield. If that does not work, uninstall the VRCSDK, U#, and U# Video, then reinstall them.

**Comment by Ffuifffghbfssdkkc** [comment]
i followed these exact steps a few times but it dosent clear the errors. creating a new project works but i cant seem to clear these errors on my world and ive spent like 8hrs or something trying to do so

**Comment by MerlinVR** [comment]
Uninstall ShaderGraph

**Comment by KazyEXE** [comment]
> Uninstall ShaderGraph

I just want to say thank you you've saved me so much time
