### ISSUE TITLE
[USharpVideo] Video Player Error when trying to load.

### ISSUE THREAD

**Issue by MapleSurrup** [MerlinVR/USharpVideo#40]
I am having some issues with the USharp Video player in my vrchat world.  

I am using Version 1.0 and was previously working fine in the project and uploaded into the world. 

After making some changes recently, every time I enter play mode in Unity it pauses due to errors and I am receiving the below errors.

I deleted the entire USharp folder out of my project and reimported fresh with the exact same errors.

![image](https://user-images.githubusercontent.com/92065235/143789767-e7c34e7f-db80-46d3-a8d2-23926cc1f352.png)
![image](https://user-images.githubusercontent.com/92065235/143789896-cf9c1f73-309f-4473-aacc-4c60c30db3f7.png)

**Comment by MerlinVR** [comment]
Disable the Error Pause button as it will cause issues. Videos should still load in-game atm, video loading in editor will be fixed in then next release.
