### ISSUE TITLE
host can put link in but other people unable to add link

### ISSUE THREAD

**Issue by ChisdealHDYT** [MerlinVR/USharpVideo#42]
there is bug on latest Udonsharp or VRC SDK3 that host of lobby able post links but when Default unlocked as host have it unlocked then its locked for others.

not sure this still maintains updates or not but this is broken both platfroms from Quest and PC

**Comment by MerlinVR** [comment]
Cannot reproduce this on latest SDK and U# and nothing has changed in either for a long time regarding sync. Make sure you don't have anything that would cause network IDs to differ between different loads of your world. This can include things like having a Quest build of the world with a different object hierarchy from the PC build or having people in different uploads of the world. 

If you have a world that you can reproduce this in and you have verified that you have not done anything unsupported with the scene hierarchy, you'll probably want to make a Canny post with a link to the world that can be used for reproducing the issue as it'd be a Udon syncing issue which is not something USharpVideo could fix.

**Comment by ChisdealHDYT** [comment]
will it be cause of me adding audioLink on Pc and Quest non audiolink

**Comment by MerlinVR** [comment]
Adding/removing any gameobject is liable to break sync in the instance between the platforms. If you want to remove things for Quest you should only disable their GameObjects/Components.

**Comment by ChisdealHDYT** [comment]
ah so disable works, i try that see works

**Comment by ChisdealHDYT** [comment]
i did disabled item way, and did trick now working. thank you help
