### ISSUE TITLE
Unable to Play Audio Files

### ISSUE THREAD

**Issue by Enverex** [MerlinVR/USharpVideo#46]
Not sure if this is a limitation of the underlying engine or USharpVideo so mentioning it just in case;

Trying to play audio files fails, only video files work. While this *is* a video player, it's typical that video players can play audio files as well and it would be a nice feature to have here.

**Comment by MerlinVR** [comment]
Use the stream player to play audio files, the builtin Unity video player does not support audio files while AVPro does.
