### ISSUE TITLE
Fails to load any video in the Unity Editor (But works fine in vrchat)

### ISSUE THREAD

**Issue by RaspberryKitty1** [MerlinVR/USharpVideo#47]
Not sure if it's something with my setup or what but ever since I updated to 1.0 its just been spamming the console with errors 
but it works just fine in vrchat...
![image](https://user-images.githubusercontent.com/28585042/170703631-cf69194c-88e3-4fa6-9062-8cf182482713.png)

**Comment by jacklul** [comment]
The fix for this I believe is in unreleased v1.0.1, which can be obtained by importing `USharpVideo` folder from the repository directly to your project.

**Comment by RaspberryKitty1** [comment]
Can confirm it worked with minor tweeking with the UI
![image](https://user-images.githubusercontent.com/28585042/170809789-4cbe5c4b-7e03-48ca-9dbb-fa598b9bc8a7.png)

**Comment by RaspberryKitty1** [comment]
![image](https://user-images.githubusercontent.com/28585042/170809809-94fef104-9b31-4d92-81be-2f2239812e10.png)
