### ISSUE TITLE
Don't know how to install USharpVideo to a project made through the VRChat Creator Companion

### ISSUE THREAD

**Issue by 4Bakers** [MerlinVR/USharpVideo#48]
I installed the VRChat SDK and U# through CC and all U# dependent packages are broken. I've tried importing the packages through CC as well, but it would not let me. I'm sure there's a simple solution to this, but I can't manage to figure it out on my own.
![image](https://user-images.githubusercontent.com/50242229/175183611-069e70c1-4c08-4d04-866c-728e6564930d.png)

**Comment by MerlinVR** [comment]
Open the VRChat SDK menu dropdown and click Reload SDK. Unity breaks sometimes with that.

**Comment by 4Bakers** [comment]
![image](https://user-images.githubusercontent.com/50242229/175185339-9d10aaad-6d9d-4d79-8ad8-efbf7c1c73e1.png)

**Comment by 4Bakers** [comment]
![image](https://user-images.githubusercontent.com/50242229/175186026-eee03d14-de45-4c6a-8af1-a07903cc9b56.png)
![image](https://user-images.githubusercontent.com/50242229/175186045-218e6ce4-e938-4133-a79d-8a852a3036eb.png)

**Comment by 4Bakers** [comment]
Fair enough. Thank you so much for your time!
