### ISSUE TITLE
name space fix!!!!

### ISSUE THREAD

**Issue by blackcat1101** [MerlinVR/USharpVideo#50]
**Add " VRC.SDKBase. " BEFORE " Utilities.isValid() "**

I'm don't know if this was changed on VRC's end or what but this fixes some 'namespace' errors related to this function on the current SDK.

**Comment by MerlinVR** [comment]
Fully qualifying the namespace does not fix anything afaik. There is a `using` for SDKBase already. Unity has a bug for years with importing dlls that causes it to think the method doesn't exist sometimes. Reimporting the SDK dlls usually fixes the issue.
