### ISSUE TITLE
URL field no longer auto clears with new VRC keyboard input

### ISSUE THREAD

**Issue by AshtonSparx** [MerlinVR/USharpVideo#52]
VRChat's new update adding a paste button and allowing the VRC keyboard to appear when an input field is clicked, causes the player to no longer clear its link when a URL is pasted. This in turn, causes you to double enter URL's every time you want to change the video.

**Comment by MerlinVR** [comment]
This is a known issue with the keyboard in open beta not respecting input events properly https://vrchat.canny.io/open-beta/p/paste-function-immediately-pressing-enter-after-putting-a-link-in-possible-disab
