### ISSUE TITLE
corrupted import?

### ISSUE THREAD

**Issue by Gwion-commits** [MerlinVR/USharpVideo#53]
Hi,

So I imported the package into my unity scene for V1.0.0 and I got 107 errors in the console and I am no longer able to access the SDK - I only get the options to either Reload or Recompile.

Is there any way to fix this or has my project become corrupted?

**Comment by MerlinVR** [comment]
Delete the folder and reimport from the unitypackage on the releases page. Make sure you've installed UdonSharp and the VRCSDK as well.

**Comment by Gwion-commits** [comment]
Ah yes, sorry, the issue was that I had not installed Usharp, I thought that Usharp and Usharpvideo was the same thing. Reloading the project after importing usharp and deleting and reimporting Usharpvideo seems to have fixed the issue.

Thanks for your quick response!

**Comment by MerlinVR** [comment]
👍
