### ISSUE TITLE
.\USharpVideoPlayer.cs(1485,28): System.Exception: 'VideoScreenHandler' does not contain a definition for 'UpdateVideoTexture'

### ISSUE THREAD

**Issue by PochiiBoy** [MerlinVR/USharpVideo#54]
Hello, so when I import everything. Things are fine and well. But when I import my video player (ProTv) I get this error. I went to Pro TV but they said it was a USharpVideo Problem, this is the error im getting. "Assets\USharpVideo\Scripts\USharpVideoPlayer.cs(1485,28): System.Exception: 'VideoScreenHandler' does not contain a definition for 'UpdateVideoTexture'"

![image](https://user-images.githubusercontent.com/90456148/189461927-3c0c5580-4a43-444d-b216-9f4e5c2acc7b.png)

**Comment by MerlinVR** [comment]
Have the author verify their scripts are in namespaces. If they are they should not conflict. USharpVideo has all its scripts namespaced properly. If you cannot get them to play together delete one or the other from the project.

**Comment by PochiiBoy** [comment]
ohh okay okay thank you

**Comment by PochiiBoy** [comment]
![image](https://user-images.githubusercontent.com/90456148/189474235-3c3cca68-14df-4d88-b957-97e89e1083ac.png)
I am actually having this problem with multiple video players. I have idea why though. Cause everything does look like it is namespaced correctly. Do you have any idea why it would give such an error even though the namespaces are fine?

**Comment by MerlinVR** [comment]
Make sure you have no other script with a class named VideoScreenHandler
