### ISSUE TITLE
Strange wall of errors upon importing, and another upon actually running. Player doesn't work in both build-and-test and in editor.

### ISSUE THREAD

**Issue by Nagmeister** [MerlinVR/USharpVideo#57]
On import:
![image](https://user-images.githubusercontent.com/19143451/203245354-798e4595-1ad1-4b29-a3c0-c927d1c292bc.png)
On run:
![image](https://user-images.githubusercontent.com/19143451/203245923-c967337f-244f-4c5f-82d4-903de6849ee3.png)
(part 1)
![image](https://user-images.githubusercontent.com/19143451/203246068-1f4005d5-21db-4737-9aa1-abef5d9b89c0.png)
(part 2)

I'll be honest, looking at this I have no idea what any potential fixes I can try would be. Any help? I assume something's gone wrong with the 'inputfield' class, since the built-in video players also don't work.

**Comment by MerlinVR** [comment]
Click this menu item 
![image](https://user-images.githubusercontent.com/36685500/203246653-e18275d8-25af-4355-9dfe-6a9ce1c1c02c.png)

and reimport the unitypackage for the video player

**Comment by Nagmeister** [comment]
That fixed the wall of errors. I can now set a default playlist and have it work, but trying to use the input field in the editor, in the build-and-test, or live in the uploaded world doesn't work.

**Comment by MerlinVR** [comment]
Reload the SDK until it works, Unity sucks.

**Comment by Nagmeister** [comment]
I think I'm just going to accept that my project's cursed and avoid putting a video player in for this one; can't use the text box on this or the default video players, and I've reloaded the SDK probably 30 times by now.

**Comment by MerlinVR** [comment]
You can also try deleting Unity's Library folder and restarting the editor

**Comment by Nagmeister** [comment]
I think there was just something messed up with Unity itself. That fix didn't work; what worked was making a new project through the VRCCC, importing udonsharp and the player, and then copying *everything* over to the new project - assets, scene, everything - and somehow, it decided to work. I won't question it; just gonna leave this as a lesson that sometimes, Unity just hates us
