### ISSUE TITLE
Assets\USharpVideo\Scripts\USharpVideoPlayer.cs(1484,21): error CS0234: The type or namespace name 'IsValid' does not exist in the namespace 'Utilities' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by ShreddzGaming** [MerlinVR/USharpVideo#58]
New to unity and world creation. I've Tried looking for other answers and deleting and reimporting the SDK, Udon Sharp, and USharpVideoPlayer.

**Comment by MerlinVR** [comment]
Make sure you don't have shadergraph in the project, it conflicts.

**Comment by ShreddzGaming** [comment]
That worked, thank you so much! Sorry for the late reply.
