### ISSUE TITLE
Video player overhaul

### ISSUE THREAD

**Issue by MerlinVR** [MerlinVR/USharpVideo#6]
Once Vket submissions are over, the video player needs a rewrite since it's a mess from adapting the VRCSDK player and tacking on features. Hopefully by that point VRC will have released the manual sync updates which can be used to make the video player take up a much smaller bandwidth footprint as well.

- #2 needs to be tested and integrated still, but it'd be good to show a button or something to the user that lets them retry the video indefinitely if they hit an error that they can correct.
- #4 looping option needs to be added
- Some cases where sync dies need to have more robust workarounds 
- Karaoke mode would be nice to have

**Comment by isjame** [comment]
Oh my god! I am looking for how to make vedio player tutorial  or UnityPack. I can't find it on YouTube or Google. Thank you very much indeed. I hope you can add functions like karaoke playlist in the next update! Thank you very much!

**Comment by DoggoDivine449** [comment]
A karaoke mode would be amazing! We're currently using the video player in our karaoke world and it works great. If you were able to add a karaoke mode where we could queue up a bunch of karaoke songs without one video playing over the other that would be super convenient.

**Comment by isjame** [comment]
Merry Christmas

**Comment by dragonash2019** [comment]
looks like someone "J.T." has made a playlist add-on. Basically pre-set youtube/stream links that play directly to the player. Will you be looking to include something like that in the re-write?

**Comment by Traediras** [comment]
I'd love to see a control for GI Emissive Boost built into the player as well. If I remembered a thing about C# I'd probably take a crack at doing that myself but alas, it's been years since I've done anything with it...
