### ISSUE TITLE
console errors in unity

### ISSUE THREAD

**Issue by Ffuifffghbfssdkkc** [MerlinVR/USharpVideo#61]
`Assets\USharpVideo\Scripts\USharpVideoPlayer.cs(1484,21): error CS0234: The type or namespace name 'IsValid' does not exist in the namespace 'Utilities' (are you missing an assembly reference?)`

`Assets\USharpVideo\Scripts\USharpVideoPlayer.cs(1503,18): error CS0234: The type or namespace name 'IsValid' does not exist in the namespace 'Utilities' (are you missing an assembly reference?)`

`Assets\USharpVideo\Scripts\USharpVideoPlayer.cs(1525,18): error CS0234: The type or namespace name 'IsValid' does not exist in the namespace 'Utilities' (are you missing an assembly reference?)`

`Assets\USharpVideo\Scripts\USharpVideoPlayer.cs(1557,21): error CS0234: The type or namespace name 'IsValid' does not exist in the namespace 'Utilities' (are you missing an assembly reference?)`

**i have followed the following steps adressed in the closed issue**
>This is usually due to Unity corrupting the SDK, try following the steps at https://docs.vrchat.com/docs/migrating-from-2018-lts-to-2019-lts#empty-control-panel-or-missing-vrcurlinputfield. If that does not work, uninstall the VRCSDK, U#, and U# Video, then reinstall them.

the same errors still persist howeaver when i created a new project that didnt have these issues. i would like to fix this error from my current world. thanks

**Comment by MerlinVR** [comment]
As I already replied, uninstall shadergraph

**Comment by Ffuifffghbfssdkkc** [comment]
oh that was quick. sry i didnt think you would see the other one since it was closed

**Comment by Ffuifffghbfssdkkc** [comment]
i just removed shader graph from packmanager and it still persists

**Comment by MerlinVR** [comment]
Then you have some other package or script that defines a `Utilities` namespace

**Comment by Ffuifffghbfssdkkc** [comment]
ive un installed every pkg that isnt in the same unity project as the test one wich works and im still having the same issue. i have also reinstalled udon and you video pkg but still get the same errors

**Comment by MerlinVR** [comment]
Then you probably have some script in your project that defines a Utilities namespace that you'll need to delete or change the namespace of.

**Comment by Ffuifffghbfssdkkc** [comment]
thx for letting me know but idk how to even start with that. im just starting fresh, ive wasted too much time alrdy lol
