### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by ShaggyBlackOG** [MerlinVR/USharpVideo#63]
hey I'm just learning world creation and such and I really wanna get these TVs working so I can stream my desktop I my world but when I press enter after adding a link nothing happens is there any easy way to go about fixing this?

**Comment by MerlinVR** [comment]
Hey this is usually due to a Unity bug when it's importing the VRCSDK. Try clicking the menu dropdown for `VRChat SDK > Reload SDK` and see if the input field script on the video player is recognized as a valid script properly. The input field script is on the GameObject under `USharpVideo/ControlsUI/InputField` 

![image](https://user-images.githubusercontent.com/36685500/213789816-5806398a-acbc-478b-ab32-e3ee33673aa9.png)

It should look like this if it's working:
![image](https://user-images.githubusercontent.com/36685500/213789713-d651cda6-8ad9-4e80-8284-265771379317.png)


If it's not working you'll see a missing script warning in its place. If reloading the SDK doesn't work the first time, continue clicking the Reload SDK menu item. It can take dozens of tries sometimes. If that doesn't work, try deleting your Library folder in the Unity project and restarting Unity. If that doesn't work, try a few more times. If that doesn't work, make a new project.

**Comment by ShaggyBlackOG** [comment]
thank you so much for getting back to me so soon ill try these things and get back on if i can get it fixed or not

**Comment by ShaggyBlackOG** [comment]
Will testing work with cyan or do I need to test in world to actually use it

**Comment by MerlinVR** [comment]
It depends on the video, if you replace the `EditorURLResolverShim.cs` file with this one https://github.com/MerlinVR/USharpVideo/blob/master/Assets/USharpVideo/Scripts/Editor/EditorURLResolverShim.cs it should work in editor for most videos.

**Comment by MerlinVR** [comment]
If the input field component looks like it does in my picture it is likely to work, so you can make sure it's not a missing script component, and make sure the fields are filled out the same way if you don't want to try playing videos every time you change something.

**Comment by ShaggyBlackOG** [comment]
yes my project looks exact to yours

**Comment by MerlinVR** [comment]
See if it plays videos in-game correctly.

**Comment by ShaggyBlackOG** [comment]
and im sorry i have no idea what im looking at when it comes to the scripts and alright ill upload rn

**Comment by ShaggyBlackOG** [comment]
IT WORKS not with cyan but it does in game ty so much do you know how I would get multiple linked in my world with there own UI areas to input

**Comment by MerlinVR** [comment]
If you want multiple video players across the world that play the same video, you can duplicate these objects and place them around the world: 
![image](https://user-images.githubusercontent.com/36685500/213798259-65d40213-0234-4a34-b138-1e7690f1ade4.png)


If you're duplicating audio sources you'll probably want to use the avpro only mode https://github.com/MerlinVR/USharpVideo/wiki/avpro-only 

For the volume control to work correctly you'll also need to add the new duplicated audio sources to the Audio Sources list on the VideoPlayerManager script on the `Internals` object 
![image](https://user-images.githubusercontent.com/36685500/213798377-117b5f79-06ca-4c11-b36f-73e460ca5d58.png)
![image](https://user-images.githubusercontent.com/36685500/213798418-2a4de24d-6180-40e7-8a20-30988af24a9f.png)

**Comment by ShaggyBlackOG** [comment]
What part do I need to remove for the audio to link? I almost got this all worked out now just missing the audio in one of my areas and I linked it in the audio sources

**Comment by MerlinVR** [comment]
You copy the audio sources, follow the article on avpro-only, and add the new copied audio sources to the Audio Sources array I posted an image of

**Comment by ShaggyBlackOG** [comment]
okay i got it all sorted but quest is saying things are upside down

**Comment by MerlinVR** [comment]
Replace the StandardVideoCore.cginc file with this one https://raw.githubusercontent.com/MerlinVR/USharpVideo/master/Assets/USharpVideo/Shaders/StandardVideoCore.cginc

**Comment by ShaggyBlackOG** [comment]
how do i swap those out like how do i get all that as a file

**Comment by MerlinVR** [comment]
Ctrl+S in the browser

**Comment by ShaggyBlackOG** [comment]
oh okay im so sorry you have to deal with an amature

**Comment by ShaggyBlackOG** [comment]
where do i put this...

**Comment by MerlinVR** [comment]
You replace the file with the same name. Search for it in the assets folder

**Comment by ShaggyBlackOG** [comment]
Okay its been done uploading now ill let you know if it worked!

**Comment by ShaggyBlackOG** [comment]
its still upside down only on stream mode

**Comment by MerlinVR** [comment]
Are you sure you replaced the file correctly? That's the fix for your issue.

**Comment by ShaggyBlackOG** [comment]
do I just delete it and then drag the new one in?

**Comment by MerlinVR** [comment]
Yes

**Comment by ShaggyBlackOG** [comment]
ok I did but its still upside down im using VRCDN streaming 
so I can stream my desktop I know Sovern has gotten it to work it would do this from time to time but then he said to have them rejoin and it would usually fix but that doesn't seem to be the case this time

**Comment by MerlinVR** [comment]
Are other videos not flipped? If it's an issue with your streaming setup I can't help much.

**Comment by ShaggyBlackOG** [comment]
no videos are ok i dont know about other streams but its ok on pc if its a me problem then ill figure it out

**Comment by MerlinVR** [comment]
I mean if you play videos with the stream player

**Comment by ShaggyBlackOG** [comment]
let me check

**Comment by ShaggyBlackOG** [comment]
streams dont play on quest

**Comment by ShaggyBlackOG** [comment]
only this one

**Comment by ShaggyBlackOG** [comment]
![quest nooo](https://user-images.githubusercontent.com/123196648/213842340-1e31b344-1891-47c2-a847-790021004966.PNG)
this is what they said

**Comment by MerlinVR** [comment]
Yeah dunno, if replacing the file I linked doesn't work I can't do much.

**Comment by ShaggyBlackOG** [comment]
that's ok for some reason protv  works with it now so I'm just learning how to link those now ty so much for your help and ill make sure to let all my friends know how to get this working if they have issues
