### ISSUE TITLE
YTDL -- Fresh install on new Project, no URLs work

### ISSUE THREAD

**Issue by dpr1990** [MerlinVR/USharpVideo#70]
Hi there, I freshly installed this on a new Unity project with VCC implemented. UdonSharp installed along with all other default packages.

Putting down the player prefab and hitting play, this occurs:

"[USharpVideo YTDL] Unable to find VRC YouTube-dl installation, URLs will not be resolved.
UnityEngine.Debug:LogWarning (object)
UdonSharp.Video.Internal.EditorURLResolverShim:SetupURLResolveCallback () (at Assets/USharpVideo/Scripts/Editor/EditorURLResolverShim.cs:35)"

Trying to add URLs to the playlist further cause errors pointing back to the URL failing.

 Any ideas? Thanks!

**Comment by dpr1990** [comment]
Addition: Build & Test -- video player works as expected. There's just no way to test in Unity?

**Comment by MerlinVR** [comment]
You can pull the updated https://github.com/MerlinVR/USharpVideo/blob/master/Assets/USharpVideo/Scripts/Editor/EditorURLResolverShim.cs over the old one and it'll work until there's a new release.
