### ISSUE TITLE
sounds not playing on duplicated AudioSource

### ISSUE THREAD

**Issue by Temka193** [MerlinVR/USharpVideo#71]
I copied the AudioSource and placed them around my room, I want them to play the same thing as the main one.
Added these AuidoSource's to the list of VideoPlayerManager and VRCUnityVideoPlayer respectively.
But only the main AudioSource plays. 
What is the problem?

**Comment by MerlinVR** [comment]
the Unity video player doesn't allow duplicate audio sources. You'd need to use the AVPro/Stream player. See: https://github.com/MerlinVR/USharpVideo/wiki/avpro-only

**Comment by Temka193** [comment]
the instructions say to set the Default Stream Mode checkbox, but I don’t want the stream mode, I need videos by url

**Comment by MerlinVR** [comment]
Stream mode can play videos as well.

**Comment by Temka193** [comment]
in streaming mode, my video loads endlessly. it doesn't work in the editor?

**Comment by MerlinVR** [comment]
It doesn't you need to test it in-game.

**Comment by Temka193** [comment]
Thank you
