### ISSUE TITLE
Question Playlist

### ISSUE THREAD

**Issue by MrsJessica92** [MerlinVR/USharpVideo#9]
How can I set an inital playlist/video url?
I tried already to set a url in "Video URL" property and set a tick in auto play. (for both Unity & AV Pro Video) but it doesn't work. 
I tried it with a playlist link as well a youtube video link that work when I put it in input url directly.

**Comment by MerlinVR** [comment]
![image](https://user-images.githubusercontent.com/36685500/99191284-b429b100-2720-11eb-94b7-54bbe0851d94.png)

Do not fill out URLs in the Video URL property on either of the VRC video player components, and do not tick auto play on either of them.
